### ISSUE TITLE
Test.js

### ISSUE THREAD

**Issue by emilyb7** [facn2/week2-717FAC-toDo#23]
Hi from London : )

Nice tests but...

- Lots of them are commented out? Is this because they're not working?
- Naming your tests "test1", "test2" etc. isn't a great solution. What about when you need test 1.5? Maybe you've worked this out already though... Instead I would use this space to write something descriptive like "addTodo takes an array and a todo list item and appends the item to the list" :)
- It's also nice to group similar tests together into one test block. Tests 1-4 would go nicely together, for example.
- Spacing inside your objects and arrays is a bit inconsistent. You should decide on a style you like and stick to it, e.g. on line 8 `{description: 'eat more food' }`

**Comment by veredrec** [comment]
@emilyb7 thanks! We fixed the problems. Thanks for your comments :)
