### ISSUE TITLE
Commented Tests

### ISSUE THREAD

**Issue by Karyum** [facn2/week2-717FAC-toDo#26]
https://github.com/facn2/week2-717FAC-toDo/blob/master/test.js#L10
https://github.com/facn2/week2-717FAC-toDo/blob/master/test.js#L22

You shouldn't have commented code. you should uncomment them and make the tests pass or just delete those tests

**Comment by veredrec** [comment]
@Karyum thanks, done :)

**Comment by Karyum** [comment]
@veredrec goodjob
