### ISSUE TITLE
Logic.js

### ISSUE THREAD

**Issue by emilyb7** [facn2/week2-717FAC-toDo#29]
Just a few things:

- I like how you've used `Object.assign` at line 35. Can you think of a way to improve the `addTodo` function using Object.assign to make the function cleaner and more concise?
- Variable naming: for super clear naming, pay attention to your verbs. `markArr` (line 33) would be better as `markedArr`.  And `copyTodo` (line 35) would be better as `copiedTodo`. (copyTodo sounds like a function, but you are naming an array...) (sorry, I know you're not necessarily native English speakers and so this might be hard for you, but it's something to think about :) )

**Comment by emilyb7** [comment]
Also, get rid of the comments on lines 36 and 37 😄

**Comment by m4v15** [comment]
I agree that addTodo could possibly be restructured, but is ```Object.assign``` not ES6? @emilyb7

**Comment by emilyb7** [comment]
@m4v15 I just saw @mattlub commenting about this in another repo 🙈🙈

So yes, ignore my comment everyone... Good to know about object.assign for when you start writing server side code though!

**Comment by tyeung2017** [comment]
Thanks for the heads up. 

Changed the wording in markToDO function
